#!/usr/bin/env node
'use strict';

const yo = require('caporal'),
			packageJSON = require('./package.json');

const commands = require('./lib/commands.js');

yo
	.version(packageJSON.version)
	.description(packageJSON.description)

	// default track/untrack command
	.action(commands.track)

	// edit command
	.command('edit', 'allows time and task adjustments')
	.alias('e')
	.option('-s, --start [time]', 'adjust current tracks starting time', /^\d\d:\d\d$/)
	.option('-e, --end [time]', 'adjust current tracks ending time', /^\d\d:\d\d$/)
	.option('-t, --task [taskname]', 'current task', yo.String)
	.action(commands.edit)

	// list command
	.command('list', 'lists all entries')
	.alias('l')
	.action(commands.list)

	// clear command
	.command('clear', 'removes all entries')
	.alias('c')
	.action(commands.clear);

yo.parse(process.argv);
