#!/usr/bin/env node
const app = require('commander'),
			packageJSON = require('./package.json');

// initialize app meta info
app
	.version(packageJSON.version)
	.description(packageJSON.description)
	.command('track', 'starts/stops current track, allows time and task adjustments', { isDefault: true })
	.command('list', 'lists all entries')
	.parse(process.argv);
