#!/usr/bin/env node

const app = require('commander'),
			TAFFY = require('node-taffydb').TAFFY,
			jsonfile = require('jsonfile'),
			fs = require('fs');

app.parse(process.argv);

const datafile = __dirname + '/yo.json';
const data = fs.existsSync(datafile) ? require(datafile) : {
	tracks: []
};

const db = TAFFY(data && data.tracks || []);
const tracks = db().get();

if (tracks.length) {
	data.tracks = [];
	jsonfile.writeFileSync(datafile, data, { spaces: 2 });
	console.log('\nYo, cleared ' + tracks.length + ' tracks.');
} else {
	console.log('\nNo tracks found, yo.')
}