#!/usr/bin/env node
const app = require('commander'),
			packageJSON = require('./package.json'),
			TAFFY = require('node-taffydb').TAFFY,
			jsonfile = require('jsonfile'),
			moment = require('moment'),
			timediff = require('timediff');

// initialize app meta info
app.parse(process.argv);