#!/usr/bin/env node
const app = require('commander'),
			packageJSON = require('./package.json'),
			TAFFY = require('node-taffydb').TAFFY,
			jsonfile = require('jsonfile'),
			moment = require('moment'),
			fs = require('fs');

app
	.option('-s, --start [time]', 'adjust current tracks starting time')
	.option('-e, --end [time]', 'adjust current tracks ending time')
	.option('-t, --task [taskname]', 'current task')
	.parse(process.argv);

const getDate = (d) => {
	d = d && d.replace(' ', 'T');
	d = moment(d);
	return (d.isValid() ? d : moment()).format();
};

const datafile = __dirname + '/yo.json';
const data = fs.existsSync(datafile) ? require(datafile) : {
	tracks: []
};

const db = TAFFY(data && data.tracks || []);

// get last track
const last = db().last();
let track = {};

if (app.task) {
	track.task = app.task;
}

if (last && last.end || !last) {
	// create track
 
	track = {
		start: getDate(app.start)
	};

	db.insert(track);

	console.log('Yo, tracking started!');

} else {
	// end track

	if (app.start) {
		track.start = getDate(app.start);
	}

	if (!app.task || app.end) {
		track.end = getDate(app.end);
	}

	db(last.___id).update(track)

	console.log('Done, huh? Yo!');

}

// save dataset
data.tracks = db().get();
jsonfile.writeFileSync(datafile, data, { spaces: 2 });
